#!/usr/bin/env zsh


# load loader
. "${GIT_DIR:-"$(dirname -- "$(dirname -- "$(realpath $0)")")"}/lib/loader/loader.zsh"

# echo "GIT_DIR begin: ${GIT_DIR}"  # delete after debug
# echo "${GIT_DIR:-"$(dirname -- "$(dirname -- "$(realpath $0)")")"}"  # delete after debug
include "${GIT_DIR:-"$(dirname -- "$(dirname -- "$(realpath $0)")")"}/lib/env"
# echo "GIT_DIR finally: ${GIT_DIR}"  # delete after debug

# include directories to search path
loader_addpath "${GIT_DIR}/lib" "${GIT_DIR}/hooks"

# init logger
include "${GIT_DIR}/lib/logger/logger.zsh"

# load main script
# Load the function
include "${GIT_DIR}/lib/invoke-hooks"
include "${GIT_DIR}/lib/hooks"

# init config env
include "${GIT_DIR}/lib/config.env"

readonly hook="$(realpath $0)"
readonly hook_type="$(basename -- "$(realpath $0)")"

main() {
  invokeClonedReposCommitMsgHook $@
}

debug "${hook_type}: Hello!"
main "$@"

loader_finish

exit 0
