#!/usr/bin/env zsh

# This hook can be used to save metadata about where a git repository
# is cloned locally.  The intent is to use this information in other
# scripts that operate on the cloned git repository.
# path to the newly cloned repo on disk


echo "GIT_DIR begin: ${GIT_DIR}"  # delete after debug
echo "${GIT_DIR:-"$(dirname -- "$(dirname -- "$(realpath $0)")")"}"  # delete after debug
. "${GIT_DIR:-"$(dirname -- "$(dirname -- "$(realpath $0)")")"}/lib/env"
echo "GIT_DIR finally: ${GIT_DIR}"  # delete after debug

# load loader
. "${GIT_DIR}/lib/loader/loader.zsh"

# include directories to search path
loader_addpath "${GIT_DIR}/lib" "${GIT_DIR}/hooks"

# init logger
include "${GIT_DIR}/lib/logger/logger.zsh"

# load main script
# Load the function
include "${GIT_DIR}/lib/invoke-hooks"
include "${GIT_DIR}/lib/hooks"

# init config env
include "${GIT_DIR}/lib/config.env"

readonly hook="$(realpath $0)"
readonly hook_type="$(basename -- "$(realpath $0)")"


main() {
  invokeClonedReposPostCheckoutHook
}

debug "${hook_type}: Hello!"
main "$@"

loader_finish

exit 0
