#!/usr/bin/env zsh

# This hook can be used to save metadata about where a git repository
# is cloned locally.  The intent is to use this information in other
# scripts that operate on the cloned git repository.
# path to the newly cloned repo on disk


export GIT_DIR=${GIT_DIR:-"$(dirname -- "$(dirname -- "$(realpath $0)")")"}

# load loader
. "${GIT_DIR}/lib/loader/loader.zsh"

# include directories to search path
loader_addpath "${GIT_DIR}/lib" "${GIT_DIR}/hooks"

# init logger
include "${GIT_DIR}/lib/logger/logger.zsh"

# load main script
# Load the function
include "${GIT_DIR}/lib/invoke-hooks"
include "${GIT_DIR}/lib/hooks"

# init env
include "${GIT_DIR}/lib/env"

readonly hook="$(realpath $0)"
readonly hook_type="$(basename -- "$(realpath $0)")"


main() {
  # rm -rf -- "${repo}/.git/hooks/post-checkout"
  # initializeSubmodules
  # installClonedReposHooks
  invokeClonedReposPostCheckoutHook
}

debug "${hook_type}: Hello!"
main "$@"

loader_finish

exit 0
